name: vagrant-up

on: [push]

jobs:
  vagrant-up:
    runs-on: self-hosted

    steps:
#    - name: install packages
#      run: |
#        sudo apt-get update && sudo apt-get install -yq virtualbox
#        curl -O https://releases.hashicorp.com/vagrant/2.2.9/vagrant_2.2.9_x86_64.deb
#        sudo apt install -yq ./vagrant_2.2.9_x86_64.deb
    - uses: actions/checkout@v2
    - name: Show Vagrant version
      run: vagrant --version
    - name: Run vagrant up
      run: vagrant up
#    - name: ssh into box after boot
#      run: vagrant ssh -c "echo 'hello world!'"
    - name: package box
      run: vagrant package ubuntu
