name: vm-provision

on: [push]

jobs:
  vagrant-provision:
    runs-on: self-hosted

    steps:
#    - name: install packages
#      run: |
#        sudo apt-get update && sudo apt-get install -yq virtualbox
#        curl -O https://releases.hashicorp.com/vagrant/2.2.9/vagrant_2.2.9_x86_64.deb
#        sudo apt install -yq ./vagrant_2.2.9_x86_64.deb
    - name: clean up old VMs
      run: | 
        vboxmanage list vms | \
        grep -o -P '(?<={).*(?=})' | \
        while read line ; do vboxmanage unregistervm $line --delete ; done
    - uses: actions/checkout@v2
    - name: show Vagrant version
      run: vagrant --version
    - name: run vagrant up
      run: |
        vagrant up
        echo "=> Vagrant run finished."
#    - name: ssh into box after boot
#      run: vagrant ssh -c "echo 'hello world!'"
#    - name: package box
#      run: |
#        vagrant halt
#        vagrant package
    - name: export virtualbox VM
      run: |
        vagrant halt
        vboxmanage export emoflon -o emoflon.ova
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: emoflon-ova
        path: emoflon.ova
    - name: clean up VM afterwards
      run: | 
        vboxmanage unregistervm emoflon --delete

  # Create a release if running on tag
  create-release:
    needs: [vagrant-provision]
    runs-on: ubuntu-20.04
    # Only run on pushed tags (and explicitely ignore scheduled runs)
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/') && github.event_name != 'schedule'
    steps:
      - name: collect artifacts
        uses: actions/download-artifact@master
      - name: create splitted ZIP archive
        run: |
          apt install -yq zip
          zip -r -s 2000m emoflon-vm.zip emoflon-ova/emoflon.ova
      - name: release emoflon-vm
        uses: softprops/action-gh-release@v1
        with:
          body: "The VM archive can not be directly added to this release because of the size limitation of 2GB per file. Please download the splitted ZIP archive and extract it manually."
          files: |
            emoflon-vm.zip
            emoflon-vm.z01
            emoflon-vm.z02
